### ISSUE TITLE
Implement partial failure on SqsConsumer

### ISSUE THREAD

**Issue by tyx** [brefphp/symfony-messenger#57]
Since brefphp has now support for partial batch failure, (https://github.com/brefphp/bref/pull/1113) I was pretty confident to implement it into the [SqsConsumer](https://github.com/brefphp/symfony-messenger/blob/master/src/Service/Sqs/SqsConsumer.php).

Except I'm not sure about the behavior we want.

Decorates the whole loop iteration of SqsConsumer with a try cach and markAsFailed $record in catch block looks a good idea at the first glance. But doing this will prevent to reach the [stopfailure](https://github.com/brefphp/bref/blob/master/src/Runtime/LambdaRuntime.php#L95) method that currently log the exception. So it will lead to losing this log.

I'm available to make the implementation but if anyone comes with a better idea how handle it, it would be great.

**Comment by t-richard** [comment]
Thanks for opening this issue, I've been willing to implement this for a while too.

The behaviour you suggest seems the right one but we don't want to reach `signalFailure` in the LambdaRuntime because I think that would be interpreted as a complete batch failure by the Lambda service. I think injecting the Logger in the Sqs handler could be enough?

But I think we need to put this new feature behind a feature flag because it can't be enabled by default as it's a change in the behaviour which requires configuration in AWS to work.

What do you think?

**Comment by tyx** [comment]
Hello @t-richard ,

You're right about signalFailure ! Injecting logger inside SqsConsumer looks a good alternative. 

I just noticed Logger is already injected in SimpleBusDriver, We could also imagine keeping logging overthere https://github.com/brefphp/symfony-messenger/blob/master/src/Service/SimpleBusDriver.php#L27 ? 

And of course I'm +1 about feature flag !

**Comment by t-richard** [comment]
@tyx FYI, I started to work on this. I'll hopefully be able to send a PR soon

**Comment by t-richard** [comment]
@tyx I just opened #58, would love your feedback on this.
